apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # This data must be Base64 encoded
  # Ee can use CLI tools or this website (https://www.base64encode.org/) to encode/decode
  mongo-user: bW9uZ291c2Vy # -> mongouser
  mongo-password: bW9uZ29wYXNzd29yZA== # -> mongopassword
